name=Type VIIC
desc=Type VII U-boats were the most common type of German World War II U-boat. 703 boats were built by the end of the war. The lone surviving example, U-995, is on display at the Laboe Naval Memorial located in Laboe, Schleswig-Holstein, Germany.
#texture folder name
texture=Type7
#low quality mesh
mesh_low=type7.obj
#high quality mesh
mesh_high=type7.obj
#top speed surfaced (knots)
surf_speed=17.7
#top speed submerged (knots)
submerged_speed=7.6
#acceleration in knots per second squared
acceleration=0.3
#tier 0 = potato. 1 = ww2 capability. 2 = early cold war. 3 = late cold war and modern. 4 = advanced futuristic
tier=1
#Length (meters):	
length=67.2
#Beam (meters)	
beam=6.2
#Draught (meters)	
draught=4.74
#displacement tonns (type 7 is 769)
disp=769
#nautical miles per gallon of fuel (type 7 is 9.8)
fuel_mpg=9.8
#propulsion type 0 = electic & disel. 1 = electric and diesel where diesel is only used for battery charging and not propulsion. 3 = nuclear
power_type=0
#range (nautical miles), at (speed in knots)
range=9800
#gallons of fuel
fuel_capacity=1000
#amp hours (type 7 has 6940-9160)
bat_amphours=6940
#electric range at 1/4th submerged top speed (in nautical miles)
bat_range=80
#Complement (sailors, pettyofficers, officers)
sailors=35
pos=12
officers=5
#num bow torpedo tubes
bow_tubes=4
#num stern torpedo tubes
stern_tubes=1
#front torpedo reserve
bow_reserve=8
#rear torpedo reserve
stern_reserve=1
#nuclear output (in MW)
nuke_pwr=2
#num years per fuel rod
nuke_efficiency=37
#can be upgraded to nuclear (bool)
can_have_nuclear=1
#can have oxygen generator retrofit (int. 0 = no, 1 = yes, 2 = yes, by default)
oxygen_gen=1
#can have passive sonar (int. 0 = no, 1 = yes, 2 = yes, by default)
passive_sonar=2
#can have active sonar
active_sonar=1
#can have radar (int. 0 = no, 1 = yes, 2 = yes, by default)
radar=1
#can have lidar (int. 0 = no, 1 = yes, 2 = yes, by default)
lidar=1
#can have snorkel (int. 0 = no, 1 = yes, 2 = yes, by default)
snorkel=1
#speed multiplier when using diesels underwater(double)
diesels_mult_water=0.82
#submarine size (for upgrade part compatibility checks. options are 0 = small. 1 = medium. 2 = large)
submarine_size=2
#can have deck gun (bool)
deckgun=1
#deck gun screen position (x,y)
deckgunX=0
deckgunY=0
#cost
cost=320000
#crush depth
max_depth=290
#test depth
safe_depth=230
#how long (in days) can the ship provide breathable air to a full complement of crew
air_amount=2
#cargo space (how many inventory slots)
cargo=30
#compartment data (5 lines per room)
#display name
#room type 0=bow torpedo. 1=stern torpedo. 2=diesel engines. 3=electric engines. 4=crew quarters. 5=command room. 6=radio room. 7=cargo. 8=stripper pole. 9=science lab. 10=nuclear reactor
#crew (total number of crew slots)
#officers
#manpower to run (defined as: how many well-rested level 5 seamen does it take to run at the room's maximum efficiency)
#texture pos x
#texture pos y
#
compartment
bow torpedo
0
15
1
8
679
98
#
compartment
bow crew quarters
4
16
0
1
570
92
#
compartment
radio room
6
2
0
2
544
92
#
compartment
command room
5
6
3
4
438
92
#
#
compartment
stern crew quarters
14
10
0
1
365
93
#
#
compartment
diesel engine room
2
10
0
5
263
95
#
#
compartment
electric engines
3
10
0
5
213
97
#
#
compartment
stern torpedo
1
6
0
2
125
98
#be sure to put "end" at the end of submarine files.
#the end keyword needs to always be 1 uncommented line under the last compartment entry
end