name=Type XXI
desc=a German diesel-electric submarine
#texture folder name
texture=Type21
#low quality mesh
mesh_low=type21.obj
#high quality mesh
mesh_high=type21.obj
#top speed surfaced (knots)
surf_speed=15.6
#top speed submerged (knots)
submerged_speed=17.2
#acceleration in knots per second squared
acceleration=0.3
#tier 0 = potato. 1 = ww2 capability. 2 = early cold war. 3 = late cold war and modern. 4 = advanced futuristic
tier=2
#Length (meters):	
length=76.7
#Beam (meters)	
beam=8.0
#Draught (meters)	
draught=6.32
#displacement tonns (type 7 is 769)
disp=1621
#nautical miles per gallon of fuel (type 7 is 9.8)
fuel_mpg=5
#propulsion type 0 = electic & disel. 1 = electric and diesel where diesel is only used for battery charging and not propulsion. 3 = nuclear
power_type=0
#range (nautical miles), at (speed in knots)
range=15500
#gallons of fuel
fuel_capacity=4736
#amp hours (type 7 has 6940-9160)
bat_amphours=33900
#electric range at 1/4th submerged top speed (in nautical miles)
bat_range=340
#Complement (sailors, pettyofficers, officers)
sailors=35
pos=12
officers=5
#num bow torpedo tubes
bow_tubes=6
#num stern torpedo tubes
stern_tubes=0
#front torpedo reserve
bow_reserve=17
#rear torpedo reserve
stern_reserve=0
#nuclear output (in MW)
nuke_pwr=10
#num years per fuel rod
nuke_efficiency=37
#can be upgraded to nuclear (bool)
can_have_nuclear=1
#can have oxygen generator retrofit (int. 0 = no, 1 = yes, 2 = yes, by default)
oxygen_gen=1
#can have passive sonar (int. 0 = no, 1 = yes, 2 = yes, by default)
passive_sonar=2
#can have active sonar
active_sonar=0
#can have radar (int. 0 = no, 1 = yes, 2 = yes, by default)
radar=1
#can have lidar (int. 0 = no, 1 = yes, 2 = yes, by default)
lidar=1
#can have snorkel (int. 0 = no, 1 = yes, 2 = yes, by default)
snorkel=2
#speed multiplier when using diesels underwater(double)
diesels_mult_water=0.95
#submarine size (for upgrade part compatibility checks. options are 0 = small. 1 = medium. 2 = large)
submarine_size=2
#can have deck gun (bool)
deckgun=0
#deck gun screen position (x,y)
deckgunX=0
deckgunY=0
#cost
cost=50000000
#crush depth
max_depth=291
#test depth
safe_depth=240
#how long (in days) can the ship provide breathable air to a full complement of crew
air_amount=6.5
#cargo space (how many inventory slots)
cargo=90
#compartment data (5 lines per room)
#display name
#room type 0=bow torpedo. 1=stern torpedo. 2=diesel engines. 3=electric engines. 4=crew quarters. 5=command room. 6=radio room. 7=cargo. 8=stripper pole. 9=science lab. 10=nuclear reactor
#crew (total number of crew slots)
#officers
#manpower to run (defined as: how many well-rested level 5 seamen does it take to run at the room's maximum efficiency)
#texture pos x
#texture pos y
#
compartment
bow torpedo
0
20
1
11
733
103
#
compartment
bow crew quarters
4
20
0
1
622
104
#
compartment
radio room
6
2
0
2
576
105
#
compartment
command room
5
6
3
4
487
104
#
#
compartment
stern crew quarters
14
20
0
1
411
104
#
#
compartment
diesel engine room
2
14
0
8
229
106
#
#
compartment
electric engines
3
14
6
1
90
120
#
#be sure to put "end" at the end of submarine files.
#the end keyword needs to always be 1 uncommented line under the last compartment entry
end